pipeline {
    agent { docker { image "centos:7" } }
    stages {
        stage('configure') {
            steps {
                sh '''
                    export http_proxy=http://proxy.ncbs.res.in:3128/
                    export https_proxy=http://proxy.ncbs.res.in:3128/
                    yum -y update
                    yum install -y cmake git libboost-dev
                    yum install -y gcc-c++
                    '''
            }
        }
        stage('build') {
            steps {
                sh '''
                    mkdir build
                    cd build
                    cmake ..
                    make -j5
                    '''
            }
        }
    }
}
