name: Windows Build

on: [push]

jobs:
  build:

    runs-on: windows-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v2
    - name: "Setup Python ${{ matrix.python-version }}"
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    # Runs a set of commands using the runners shell
    - name: Build using MSVS
      shell: bash
      run: |
        mkdir build
        cd build
        PYTHON=$(which python)
        $PYTHON -m pip install pip wheel setuptools --upgrade
        $PYTHON -m pip install numpy pytest matplotlib 
        $PYTHON -m pip install python-libsbml pyneuroml
        cmake -DPython3_EXECUTABLE=$PYTHON ..
        cmake --build . --config Release
        ctest -R core_test.* -C Release --output-on-failure || echo "Tests failed"

    - name: Upload to PyPI
      shell: bash
      env:
        MOOSE_PYPI_TOKEN: ${{ secrets.MOOSE_PYPI_TOKEN }}
      run: |
        cd build
        python -m pip install twine --upgrade
        python -m twine upload -u __token__ -p "$MOOSE_PYPI_TOKEN" *.whl --skip-existing || echo "Failed to upload"
